### ISSUE TITLE
Not proper expression for formula (7) in Bulletproofs+？

### ISSUE THREAD

**Issue by 3for** [ZenGo-X/bulletproofs#25]
I‘m reading the paper [Bulletproofs+: Shorter Proofs for Privacy-Enhanced Distributed Ledger](https://eprint.iacr.org/2020/735.pdf), formular (7) in Page 5 is using `z` to combine the three contraints into one, but I don't think the expression is right for the following reason:
![image](https://user-images.githubusercontent.com/30716372/92341795-590c8a00-f0f1-11ea-8c1f-def739b82a0d.png)

![image](https://user-images.githubusercontent.com/30716372/92341818-78a3b280-f0f1-11ea-8e00-bce05c2bdb7f.png)

OR anything wrong for my comprehension?

**Comment by suyash67** [comment]
Hi @3for!

In Bulletproofs, the constraints are combined using scalars `z^2, z, 1`. Bulletproofs+ paper combines them using `y^{n+1}, z, 1`. As long as you combine the constraints using any scalars (or powers of scalars), it is fine. 

What you are doing is also right, but for the first equation you don't need to multiply it with `z^2` as we already multiply it by `y^{n+1}` to bring it to weighted inner product form.

Read my [blog](https://suyash67.github.io/homepage/project/2020/07/03/bulletproofs_plus_part2.html) to understand the detailed steps. Hope this helps.

**Comment by 3for** [comment]
@suyash67 Thanks for your reply. It's helpful.
